name: Bug Report
description: File a bug report
title: "[Bug] "
labels: ["type:bug-suspected", "Needs: Triage :mag:"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    attributes:
      label: Current Behavior
      description: |
        A concise description of what you're experiencing.
        
        Tip: You can attach images by clicking this area to highlight it and then dragging files in, or copy and paste from the clipboard.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: |
        A concise description of what you expected to happen.
                
        Tip: You can attach images by clicking this area to highlight it and then dragging files in, or copy and paste from the clipboard.        
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: WikiTraccs Version
      description: |
        What version of WikiTraccs are you running?
        Note: Issues for the WikiPakk page tree should be created in the [WikiPakk repository](https://github.com/WikiTransformationProject/wikitraccs-wikipakk-releases).
      placeholder: v1.x.y
    validations:
      required: true  
  - type: dropdown
    id: confluence-version
    attributes:
      label: Confluence Version
      description: What version of Confluence are you migrating?
      options:
        - Confluence 6
        - Confluence 7 (up to 7.17)
        - Confluence 7 (7.18 or newer)
        - Confluence 8
        - Confluence Cloud
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Confluence Data Center?
      description: If you are on-premises, knowing the edition might help diagnose issues.
      options:
      - label: This is about Confluence Data Center
        required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output or page storage format
      description: |
        Please copy and paste any relevant logs or page storage formats.
        Have a look at the [Troubleshooting Strategies](https://www.wikitransformationproject.com/docs/troubleshooting/troubleshooting-strategies/#which-information-is-available-to-diagnose-issues) page for an overview of available log files.
        Have a look at the [Get the Confluence Storage Format](https://www.wikitransformationproject.com/docs/troubleshooting/troubleshooting-strategies/get-confluence-storage-format) page to learn how to get the storage format of a page.
        Send confidential log files to contact@wikitransformationproject.com instead and reference this issue! Log files always help.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
